version: 2.1
orbs:
  node: circleci/node@6.1.0
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  build:
    executor: node/default
    steps:
      - checkout
      - run: sudo npm install -g npm@latest
      - node/install-packages:
          cache-path: ~/project/node_modules
          override-ci-command: npm install
      - sonarcloud/scan
      
workflows:
  main: 
    jobs:
      - build:
          context: SonarCloud